import type { ProfileConfig, SectionKey } from "../domain/profile";
import {
  cleanText,
  escapeMarkdownText,
  escapeTableCell,
  escapeXml,
  inlineCode,
  safeHttpsUrl,
  sanitizeMarkdown,
} from "./escape";
import { heroFilename } from "./svg";

function slugForSection(section: SectionKey): string {
  return section === "repositories" ? "selected-work" : section;
}

function headingForSection(config: ProfileConfig, section: SectionKey): string {
  switch (section) {
    case "about":
      return config.about.heading;
    case "repositories":
      return config.sectionHeadings.repositories;
    case "skills":
      return config.sectionHeadings.skills;
    case "links":
      return config.sectionHeadings.links;
    case "custom":
      return config.custom.heading;
  }
}

function renderAbout(config: ProfileConfig): string {
  const paragraphs = config.about.paragraphs
    .map((paragraph) => escapeMarkdownText(paragraph))
    .join("\n\n");
  const process = config.about.processLine
    ? `\n\n\`\`\`text\n${cleanText(config.about.processLine).replaceAll("```", "ˋˋˋ")}\n\`\`\``
    : "";
  return `## ${escapeMarkdownText(config.about.heading)}\n\n${paragraphs}${process}`;
}

function renderRepositories(config: ProfileConfig): string {
  if (config.repositories.length === 0) return "";
  const rows = config.repositories
    .map(
      (repository) =>
        `| **[${escapeTableCell(repository.name)}](${safeHttpsUrl(repository.url)})** | ${escapeTableCell(repository.description)} | ${escapeTableCell(repository.focus)} |`,
    )
    .join("\n");
  return `## ${escapeMarkdownText(config.sectionHeadings.repositories)}\n\n| Project | What it does | Focus |\n| :--- | :--- | :--- |\n${rows}`;
}

function renderSkills(config: ProfileConfig): string {
  if (config.skillGroups.length === 0) return "";
  const groups = config.skillGroups
    .map(
      (group) =>
        `**${escapeMarkdownText(group.label)}**  \n${group.items.map(inlineCode).join(" ")}`,
    )
    .join("\n\n");
  return `## ${escapeMarkdownText(config.sectionHeadings.skills)}\n\n${groups}`;
}

function renderLinks(config: ProfileConfig): string {
  if (config.links.length === 0) return "";
  const links = config.links
    .map((link) => `[${escapeMarkdownText(link.label)}](${safeHttpsUrl(link.url)})`)
    .join(" &nbsp; / &nbsp; ");
  return `## ${escapeMarkdownText(config.sectionHeadings.links)}\n\n${links}`;
}

function renderCustom(config: ProfileConfig): string {
  if (!config.custom.heading || !config.custom.markdown.trim()) return "";
  return `## ${escapeMarkdownText(config.custom.heading)}\n\n${sanitizeMarkdown(config.custom.markdown)}`;
}

function renderSection(config: ProfileConfig, section: SectionKey): string {
  let content: string;
  switch (section) {
    case "about":
      content = renderAbout(config);
      break;
    case "repositories":
      content = renderRepositories(config);
      break;
    case "skills":
      content = renderSkills(config);
      break;
    case "links":
      content = renderLinks(config);
      break;
    case "custom":
      content = renderCustom(config);
      break;
  }
  return content ? `<a id="${slugForSection(section)}"></a>\n${content}` : "";
}

export function renderReadme(config: ProfileConfig): string {
  const alt = escapeXml(
    config.accessibility.imageAlt ||
      `${config.identity.displayName} — ${config.identity.primaryRole}. ${config.hero.headline.join(" ")} Terminal illustration of demo checks; not live results.`,
  );
  const nav = config.sections
    .filter((section) => Boolean(renderSection(config, section)))
    .map(
      (section) =>
        `<a href="#${slugForSection(section)}">${escapeXml(headingForSection(config, section))}</a>`,
    )
    .join(" &nbsp; / &nbsp; ");
  const content = config.sections
    .map((section) => renderSection(config, section))
    .filter(Boolean)
    .join("\n\n");
  const footer =
    config.footer.emphasis || config.footer.line
      ? `\n\n---\n\n<p align="center">\n  <sub>${config.footer.emphasis ? `<b>${escapeXml(config.footer.emphasis)}</b>` : ""}${config.footer.emphasis && config.footer.line ? "<br>" : ""}${escapeXml(config.footer.line)}</sub>\n</p>`
      : "";

  return `<!-- Generated by Animated GitHub Profile Studio. Edit profile.config.json, then regenerate. -->
<picture>
  <source media="(max-width: 600px) and (prefers-reduced-motion: reduce) and (prefers-color-scheme: dark)" srcset="./assets/${heroFilename({ viewport: "mobile", theme: "dark", motion: "static" })}">
  <source media="(max-width: 600px) and (prefers-reduced-motion: reduce) and (prefers-color-scheme: light)" srcset="./assets/${heroFilename({ viewport: "mobile", theme: "light", motion: "static" })}">
  <source media="(prefers-reduced-motion: reduce) and (prefers-color-scheme: dark)" srcset="./assets/${heroFilename({ viewport: "desktop", theme: "dark", motion: "static" })}">
  <source media="(prefers-reduced-motion: reduce) and (prefers-color-scheme: light)" srcset="./assets/${heroFilename({ viewport: "desktop", theme: "light", motion: "static" })}">
  <source media="(max-width: 600px) and (prefers-color-scheme: dark)" srcset="./assets/${heroFilename({ viewport: "mobile", theme: "dark", motion: "animated" })}">
  <source media="(max-width: 600px) and (prefers-color-scheme: light)" srcset="./assets/${heroFilename({ viewport: "mobile", theme: "light", motion: "animated" })}">
  <source media="(prefers-color-scheme: dark)" srcset="./assets/${heroFilename({ viewport: "desktop", theme: "dark", motion: "animated" })}">
  <source media="(prefers-color-scheme: light)" srcset="./assets/${heroFilename({ viewport: "desktop", theme: "light", motion: "animated" })}">
  <img alt="${alt}" src="./assets/${heroFilename({ viewport: "desktop", theme: "dark", motion: "animated" })}" width="100%">
</picture>

${nav ? `<p align="center">\n  ${nav}\n</p>\n\n` : ""}${content}${footer}
`;
}
